package outrosServicos;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import projetoprog2.DataHorario;

/**
 *
 * @author Alfredo, Felipe
 */
public class JFrameOutrosServ extends javax.swing.JFrame {
    /** Creates new form JFrameAtividadeTur */
    public JFrameOutrosServ() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbasAcomodacao = new javax.swing.JTabbedPane();
        AbaTranslado = new javax.swing.JPanel();
        jLabelTranslado = new javax.swing.JLabel();
        AbaCityTour = new javax.swing.JPanel();
        jLabelCityTour = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jLabelPreco = new javax.swing.JLabel();
        jTextPreco = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jTextDescricao = new javax.swing.JTextField();
        jBIncluir = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabelDuracao = new javax.swing.JLabel();
        jTextDuracao = new javax.swing.JTextField();
        jLabelVagas = new javax.swing.JLabel();
        jTextVagas = new javax.swing.JTextField();
        jTextDia = new javax.swing.JTextField();
        jTextMes = new javax.swing.JTextField();
        jTextAno = new javax.swing.JTextField();
        jTextHora = new javax.swing.JTextField();
        jTextMinuto = new javax.swing.JTextField();
        jLabelHorario = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Serviço");
        setResizable(false);

        jLabelTranslado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTranslado.setText("Não necessita de atributos específicos.");

        javax.swing.GroupLayout AbaTransladoLayout = new javax.swing.GroupLayout(AbaTranslado);
        AbaTranslado.setLayout(AbaTransladoLayout);
        AbaTransladoLayout.setHorizontalGroup(
            AbaTransladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaTransladoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTranslado)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        AbaTransladoLayout.setVerticalGroup(
            AbaTransladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaTransladoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTranslado)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        AbasAcomodacao.addTab("Translado", AbaTranslado);

        jLabelCityTour.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCityTour.setText("Não necessita de atributos específicos.");

        javax.swing.GroupLayout AbaCityTourLayout = new javax.swing.GroupLayout(AbaCityTour);
        AbaCityTour.setLayout(AbaCityTourLayout);
        AbaCityTourLayout.setHorizontalGroup(
            AbaCityTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCityTourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCityTour)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        AbaCityTourLayout.setVerticalGroup(
            AbaCityTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaCityTourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCityTour)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        AbasAcomodacao.addTab("City Tour", AbaCityTour);

        jLabelNome.setText("Nome: ");

        jTextNome.setText("Outro Serviço");

        jLabelNumero.setText("Numero:");

        jTextNumero.setText("001");
        jTextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroActionPerformed(evt);
            }
        });

        jLabelPreco.setText("Preço:");

        jTextPreco.setText("14");

        jLabelDescricao.setText("Descrição (300 char):");

        jTextDescricao.setText("Um serviço.");
        jTextDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescricaoActionPerformed(evt);
            }
        });

        jBIncluir.setText("Incluir");
        jBIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncluirActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabelDuracao.setText("Duração (horas):");

        jTextDuracao.setText("4");
        jTextDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDuracaoActionPerformed(evt);
            }
        });

        jLabelVagas.setText("Vagas:");

        jTextVagas.setText("30");
        jTextVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVagasActionPerformed(evt);
            }
        });

        jTextDia.setText("01");
        jTextDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiaActionPerformed(evt);
            }
        });

        jTextMes.setText("02");

        jTextAno.setText("2012");
        jTextAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAnoActionPerformed(evt);
            }
        });

        jTextHora.setText("09");
        jTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHoraActionPerformed(evt);
            }
        });

        jTextMinuto.setText("45");
        jTextMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMinutoActionPerformed(evt);
            }
        });

        jLabelHorario.setText("Horário (HH:MM):");

        jLabelData.setText("Data (DD/MM/AAAA):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDescricao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelData)
                                            .addComponent(jLabelHorario))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextHora, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextDia, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextDuracao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelDuracao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextMes)
                                            .addComponent(jTextMinuto, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextAno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelVagas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelPreco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(74, 74, 74)
                        .addComponent(jTextNome, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNumero)
                        .addGap(16, 16, 16)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AbasAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCancelar, jBIncluir, jBLimpar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextDuracao, jTextPreco, jTextVagas});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextAno, jTextDia, jTextHora, jTextMes, jTextMinuto});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AbasAcomodacao, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNome)
                            .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumero))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jLabelData)
                            .addComponent(jTextDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHorario)
                            .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDuracao)
                            .addComponent(jTextDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVagas)
                            .addComponent(jTextVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPreco)
                            .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBLimpar)
                            .addComponent(jBIncluir)
                            .addComponent(jBCancelar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Limpa o conteúdo de todos os campos.
     */
    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        jTextNome.setText(null);
        jTextNumero.setText(null);
        jTextAno.setText(null);
        jTextMes.setText(null);
        jTextDia.setText(null);
        jTextHora.setText(null);
        jTextMinuto.setText(null);
        jTextDuracao.setText(null);
        jTextVagas.setText(null);
        jTextPreco.setText(null);
        jTextDescricao.setText(null);

        if(AbasAcomodacao.getSelectedComponent() == AbaTranslado)
        {
            //Não há componentes extras para a aba Translado.
        }
        else if(AbasAcomodacao.getSelectedComponent() == AbaCityTour)
        {
            //Não há componentes extras para a aba CityTour.
        }
    }//GEN-LAST:event_jBLimparActionPerformed

    /**
     * Cria o novo arquivo para incluir posteriormente nos roteiros.
     */
    private void jBIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncluirActionPerformed
        //CASO SEJA TRANSLADO.
        if (AbasAcomodacao.getSelectedComponent() == AbaTranslado){
            //Não possui atributos específicos.
            Translado novo = new Translado
                (jTextNome.getText(),
                Integer.parseInt(jTextNumero.getText()));
            novo.setDataHorario(
                    new DataHorario((byte) Integer.parseInt(jTextAno.getText()),
                    (byte) Integer.parseInt(jTextMes.getText()),
                    (byte) Integer.parseInt(jTextDia.getText()),
                    (byte) Integer.parseInt(jTextHora.getText()),
                    (byte) Integer.parseInt(jTextMinuto.getText()))
                    );
            novo.setDuracaoHora((byte) Integer.parseInt(jTextDuracao.getText()));
            novo.setVagas((byte) Integer.parseInt(jTextVagas.getText()));
            novo.setPreco(Double.parseDouble(jTextPreco.getText()));
            novo.setDescricao(jTextDescricao.getText());

            //Fluxo
            System.out.println("--------------------");
            System.out.println("Fluxo de arquivo iniciado");
            try
            {
                //Escrtitora por linha
                FileWriter out = new FileWriter("OutrosTranslado.txt", true);
                PrintWriter escreve = new PrintWriter(out);
                System.out.println("Escritora de arquivo criada.");

                //Leitora do arquivo para cadastro de novas aventuras
                FileInputStream stream = new FileInputStream("OutrosTranslado.txt");
                InputStreamReader streamReader = new InputStreamReader(stream);
                BufferedReader in = new BufferedReader(streamReader);
                System.out.println("Leitor de arquvo criado.");

                String s = null;

                //Escreve depois das linhas ja escritas
                do{
                    s = in.readLine();
                    if(s==null)
                    {
                          escreve.println(novo.getNome());
                          escreve.println(novo.getNumero());
                          escreve.println(novo.getSubTipo());
                          escreve.println(novo.getDataHorario().getAno());
                          escreve.println(novo.getDataHorario().getMes());
                          escreve.println(novo.getDataHorario().getDia());
                          escreve.println(novo.getDataHorario().getHora());
                          escreve.println(novo.getDataHorario().getMin());
                          escreve.println(novo.getDuracaoHora());
                          escreve.println(novo.getVagas());
                          escreve.println(novo.getPreco());
                          escreve.println(novo.getDescricao());

                          //Separador
                          escreve.println("//");
                          System.out.println("Entrada de dados completa.");
                    }
                }while(s != null);
                escreve.flush();
                escreve.close();
                out.close();
                streamReader.close();
                in.close();
                stream.close();

            } catch(IOException e)
            {
                 JOptionPane.showMessageDialog(null,
                        "Erro! Arquivo não pode ser criado.");
            }
            System.out.println("Fluxo de arquivo terminado.");
            System.out.println("--------------------");
        }

        //CASO SEJA CITY TOUR.
        if (AbasAcomodacao.getSelectedComponent() == AbaCityTour){
            //Não possui atributos específicos.
            CityTour novo = new CityTour
                (jTextNome.getText(),
                Integer.parseInt(jTextNumero.getText()));
            novo.setDataHorario(
                    new DataHorario((byte) Integer.parseInt(jTextAno.getText()),
                    (byte) Integer.parseInt(jTextMes.getText()),
                    (byte) Integer.parseInt(jTextDia.getText()),
                    (byte) Integer.parseInt(jTextHora.getText()),
                    (byte) Integer.parseInt(jTextMinuto.getText()))
                    );
            novo.setDuracaoHora((byte) Integer.parseInt(jTextDuracao.getText()));
            novo.setVagas((byte) Integer.parseInt(jTextVagas.getText()));
            novo.setPreco(Double.parseDouble(jTextPreco.getText()));
            novo.setDescricao(jTextDescricao.getText());

            //Fluxo
            System.out.println("--------------------");
            System.out.println("Fluxo de arquivo iniciado");
            try
            {
                //Escrtitora por linha
                FileWriter out = new FileWriter("OutrosCityTour.txt", true);
                PrintWriter escreve = new PrintWriter(out);
                System.out.println("Escritora de arquivo criada.");

                //Leitora do arquivo para cadastro de novas aventuras
                FileInputStream stream = new FileInputStream("OutrosCityTour.txt");
                InputStreamReader streamReader = new InputStreamReader(stream);
                BufferedReader in = new BufferedReader(streamReader);
                System.out.println("Leitor de arquvo criado.");

                String s = null;

                //Escreve depois das linhas ja escritas
                do{
                    s = in.readLine();
                    if(s==null)
                    {
                          escreve.println(novo.getNome());
                          escreve.println(novo.getNumero());
                          escreve.println(novo.getSubTipo());
                          escreve.println(novo.getDataHorario().getAno());
                          escreve.println(novo.getDataHorario().getMes());
                          escreve.println(novo.getDataHorario().getDia());
                          escreve.println(novo.getDataHorario().getHora());
                          escreve.println(novo.getDataHorario().getMin());
                          escreve.println(novo.getDuracaoHora());
                          escreve.println(novo.getVagas());
                          escreve.println(novo.getPreco());
                          escreve.println(novo.getDescricao());

                          //Separador
                          escreve.println("//");
                          System.out.println("Entrada de dados completa.");
                    }
                }while(s != null);
                escreve.flush();
                escreve.close();
                out.close();
                streamReader.close();
                in.close();
                stream.close();

            } catch(IOException e)
            {
                 JOptionPane.showMessageDialog(null,
                        "Erro! Arquivo não pode ser criado.");
            }
            System.out.println("Fluxo de arquivo terminado.");
            System.out.println("--------------------");
        }
}//GEN-LAST:event_jBIncluirActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroActionPerformed

    private void jTextDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDuracaoActionPerformed

    private void jTextDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescricaoActionPerformed

    private void jTextVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVagasActionPerformed

    private void jTextDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextDiaActionPerformed

    private void jTextMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMinutoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextMinutoActionPerformed

    private void jTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHoraActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextHoraActionPerformed

    private void jTextAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAnoActionPerformed

    /**
     * Cria um novo objeto derivado de Acomodacao.
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameOutrosServ().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaCityTour;
    private javax.swing.JPanel AbaTranslado;
    private javax.swing.JTabbedPane AbasAcomodacao;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBIncluir;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JLabel jLabelCityTour;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelDuracao;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelTranslado;
    private javax.swing.JLabel jLabelVagas;
    private javax.swing.JTextField jTextAno;
    private javax.swing.JTextField jTextDescricao;
    private javax.swing.JTextField jTextDia;
    private javax.swing.JTextField jTextDuracao;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextMes;
    private javax.swing.JTextField jTextMinuto;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPreco;
    private javax.swing.JTextField jTextVagas;
    // End of variables declaration//GEN-END:variables
}
