package projetoprog2;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author Blind
 */
public class Adicionar extends javax.swing.JFrame {
    String leitor;
    int i = 1;
    String arquivo = null;
    String clasificacaoHotel = null;
    boolean separador = false;
    int linhas = 0;
    int atualizaComboBox =0;
    JFramePrincipal jT;
   
    /** Creates new form Adicionar */
   
        
        
    
    public Adicionar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneAbas = new javax.swing.JTabbedPane();
        jAbaAtividadesTuristicas = new javax.swing.JPanel();
        jLabelPasso1Ativ = new javax.swing.JLabel();
        jComboBAtiv = new javax.swing.JComboBox();
        jLabelPasso2Ativ = new javax.swing.JLabel();
        jComboBAtivSelec = new javax.swing.JComboBox();
        jButtonAtulizarAtividade = new javax.swing.JButton();
        jButtonSelecionarAtividade = new javax.swing.JButton();
        jLabelNomeAtiv = new javax.swing.JLabel();
        jTextFNomeAtividade = new javax.swing.JTextField();
        jLabelNumeroAtiv = new javax.swing.JLabel();
        jTextFNumerAtividade = new javax.swing.JTextField();
        jLabelDescricaoAtiv = new javax.swing.JLabel();
        jTextFDesAtividade = new javax.swing.JTextField();
        jLabelDiaAtiv = new javax.swing.JLabel();
        jTextFDiaAtividade = new javax.swing.JTextField();
        jLabelMesAtiv = new javax.swing.JLabel();
        jTextFMesAtividade = new javax.swing.JTextField();
        jLabelAnoAtiv = new javax.swing.JLabel();
        jTextFAnoAtividade = new javax.swing.JTextField();
        jLabelHoraAtiv = new javax.swing.JLabel();
        jTextFHoraAtividade = new javax.swing.JTextField();
        jLabelMinAtiv = new javax.swing.JLabel();
        jTextFMinAtividade = new javax.swing.JTextField();
        jLabelDuracaoAtiv = new javax.swing.JLabel();
        jTextFDuracaoAtividade = new javax.swing.JTextField();
        jLabelPrecoAtiv = new javax.swing.JLabel();
        jTextFPrecoAtividade = new javax.swing.JTextField();
        jLabelLocalAtiv = new javax.swing.JLabel();
        jTextFLocalAtividade = new javax.swing.JTextField();
        jLabelAtivEspecificoA = new javax.swing.JLabel();
        jTextFAtivEspecificoA = new javax.swing.JTextField();
        jLabelAtivEspecificoB = new javax.swing.JLabel();
        jScrollPaneAtivEspecificoB = new javax.swing.JScrollPane();
        jTextAtivEspecificoB = new javax.swing.JTextPane();
        jLabelVagasAtiv = new javax.swing.JLabel();
        jTextVagasAtividade = new javax.swing.JTextField();
        jButtonCancelarAcom1 = new javax.swing.JButton();
        jButtonAdicionarAcom1 = new javax.swing.JButton();
        jAbaAcomodocacoes = new javax.swing.JPanel();
        jLabelPasso1Acom = new javax.swing.JLabel();
        jComboAcom = new javax.swing.JComboBox();
        jTextFPrecoAcom = new javax.swing.JTextField();
        jScrollPaneObsAcom = new javax.swing.JScrollPane();
        jTextAreaObsDescricoes = new javax.swing.JTextArea();
        jLabelObsAcom = new javax.swing.JLabel();
        jLabelPasso2Acom = new javax.swing.JLabel();
        jLabelLocalAcom = new javax.swing.JLabel();
        jLabelDiariaAcom = new javax.swing.JLabel();
        jButtonAtualizarAcomodacaoSelec = new javax.swing.JButton();
        jComboAcomSelec = new javax.swing.JComboBox();
        jLabelNomeAcom = new javax.swing.JLabel();
        jTextFNomeAcom = new javax.swing.JTextField();
        jLabelNumeroAcom = new javax.swing.JLabel();
        jTextFNumeroAcom = new javax.swing.JTextField();
        jLabelQuartosAcom = new javax.swing.JLabel();
        jTextFQuartosAcom = new javax.swing.JTextField();
        jLabelClassifAcom = new javax.swing.JLabel();
        jTextFClasifAcom = new javax.swing.JTextField();
        jButtonAdicionarAcom = new javax.swing.JButton();
        jButtonSelecionarAcomodacao = new javax.swing.JButton();
        jTextFLocalAcom = new javax.swing.JTextField();
        jLabelAcomEspecificoA = new javax.swing.JLabel();
        jScrollPaneAcomEspecificoA = new javax.swing.JScrollPane();
        jTextAreaAcomEspecificoA = new javax.swing.JTextArea();
        jButtonCancelarAcom = new javax.swing.JButton();
        jTextFMinServ = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonAtuServ = new javax.swing.JButton();
        jComboBServ = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFNomeServ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFNumServ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFClasServ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFVagasServ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFPrecoServ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFDiaServ = new javax.swing.JTextField();
        jTextFMesServ = new javax.swing.JTextField();
        jTextFAnoServ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFDurServ = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFHoraServ = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextADescServ = new javax.swing.JTextArea();
        jAbaDescontos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar ítem ao roteiro");

        jAbaAtividadesTuristicas.setMaximumSize(new java.awt.Dimension(800, 600));
        jAbaAtividadesTuristicas.setPreferredSize(new java.awt.Dimension(455, 488));

        jLabelPasso1Ativ.setText("Passo 1: Selecione o subtipo:");

        jComboBAtiv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aventura", "Cultural", "Passeio", "Alimentacao" }));
        jComboBAtiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBAtivActionPerformed(evt);
            }
        });

        jLabelPasso2Ativ.setText("Passo 2: Selecione um ítem para visualizá-lo:");

        jComboBAtivSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBAtivSelecActionPerformed(evt);
            }
        });

        jButtonAtulizarAtividade.setText("Atualizar");
        jButtonAtulizarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtulizarAtividadeActionPerformed(evt);
            }
        });

        jButtonSelecionarAtividade.setText("Selecionar");
        jButtonSelecionarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarAtividadeActionPerformed(evt);
            }
        });

        jLabelNomeAtiv.setText("Nome:");

        jTextFNomeAtividade.setEditable(false);

        jLabelNumeroAtiv.setText("Numero:");

        jTextFNumerAtividade.setEditable(false);

        jLabelDescricaoAtiv.setText("Descrição: ");

        jTextFDesAtividade.setEditable(false);

        jLabelDiaAtiv.setText("Dia:");

        jTextFDiaAtividade.setEditable(false);

        jLabelMesAtiv.setText("Mês:");

        jTextFMesAtividade.setEditable(false);

        jLabelAnoAtiv.setText("Ano:");

        jTextFAnoAtividade.setEditable(false);

        jLabelHoraAtiv.setText("Hora:");

        jTextFHoraAtividade.setEditable(false);

        jLabelMinAtiv.setText("Min:");

        jTextFMinAtividade.setEditable(false);

        jLabelDuracaoAtiv.setText("Duração:");

        jTextFDuracaoAtividade.setEditable(false);

        jLabelPrecoAtiv.setText("Preço:");

        jTextFPrecoAtividade.setEditable(false);

        jLabelLocalAtiv.setText("Local:");

        jTextFLocalAtividade.setEditable(false);

        jLabelAtivEspecificoA.setText("Dificuldade:");

        jTextFAtivEspecificoA.setEditable(false);

        jLabelAtivEspecificoB.setText("Restrições:");

        jTextAtivEspecificoB.setEditable(false);
        jScrollPaneAtivEspecificoB.setViewportView(jTextAtivEspecificoB);

        jLabelVagasAtiv.setText("Vagas:");

        jTextVagasAtividade.setEditable(false);

        jButtonCancelarAcom1.setText("Cancelar");
        jButtonCancelarAcom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAcom1ActionPerformed(evt);
            }
        });

        jButtonAdicionarAcom1.setText("Adicionar");
        jButtonAdicionarAcom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAcom1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAbaAtividadesTuristicasLayout = new javax.swing.GroupLayout(jAbaAtividadesTuristicas);
        jAbaAtividadesTuristicas.setLayout(jAbaAtividadesTuristicasLayout);
        jAbaAtividadesTuristicasLayout.setHorizontalGroup(
            jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                        .addComponent(jScrollPaneAtivEspecificoB, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarAcom1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdicionarAcom1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAbaAtividadesTuristicasLayout.createSequentialGroup()
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAtivEspecificoB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPasso1Ativ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBAtivSelec, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBAtiv, javax.swing.GroupLayout.Alignment.LEADING, 0, 241, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSelecionarAtividade)
                                    .addComponent(jButtonAtulizarAtividade)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNomeAtiv)
                                    .addComponent(jLabelDescricaoAtiv))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFDesAtividade)
                                    .addComponent(jTextFNomeAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDuracaoAtiv)
                                    .addComponent(jLabelNumeroAtiv)
                                    .addComponent(jLabelVagasAtiv))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextVagasAtividade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFDuracaoAtividade)
                                    .addComponent(jTextFNumerAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                .addComponent(jLabelPasso2Ativ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDiaAtiv)
                                    .addComponent(jLabelHoraAtiv))
                                .addGap(18, 18, 18)
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                        .addComponent(jTextFDiaAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelMesAtiv)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFMesAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelAnoAtiv))
                                    .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                        .addComponent(jTextFHoraAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelMinAtiv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFMinAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFAnoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFAtivEspecificoA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                                .addComponent(jLabelPrecoAtiv)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFPrecoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jAbaAtividadesTuristicasLayout.createSequentialGroup()
                                .addComponent(jLabelLocalAtiv)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFLocalAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelAtivEspecificoA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)))
                        .addGap(135, 135, 135)))
                .addContainerGap())
        );

        jAbaAtividadesTuristicasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAtulizarAtividade, jButtonSelecionarAtividade});

        jAbaAtividadesTuristicasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFDiaAtividade, jTextFMesAtividade});

        jAbaAtividadesTuristicasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFHoraAtividade, jTextFMinAtividade});

        jAbaAtividadesTuristicasLayout.setVerticalGroup(
            jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPasso1Ativ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtulizarAtividade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPasso2Ativ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBAtivSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecionarAtividade))
                .addGap(18, 18, 18)
                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomeAtiv)
                            .addComponent(jTextFNomeAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDescricaoAtiv)
                            .addComponent(jTextFDesAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDiaAtiv)
                            .addComponent(jTextFDiaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMesAtiv)
                            .addComponent(jTextFMesAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnoAtiv)
                            .addComponent(jTextFAnoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHoraAtiv)
                            .addComponent(jTextFHoraAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMinAtiv)
                            .addComponent(jTextFMinAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroAtiv)
                            .addComponent(jTextFNumerAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDuracaoAtiv)
                            .addComponent(jTextFDuracaoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVagasAtiv)
                            .addComponent(jTextVagasAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFPrecoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrecoAtiv))))
                .addGap(18, 18, 18)
                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLocalAtiv)
                        .addComponent(jTextFLocalAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAtivEspecificoA))
                    .addComponent(jTextFAtivEspecificoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jAbaAtividadesTuristicasLayout.createSequentialGroup()
                        .addComponent(jLabelAtivEspecificoB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneAtivEspecificoB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jAbaAtividadesTuristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCancelarAcom1)
                        .addComponent(jButtonAdicionarAcom1)))
                .addGap(92, 92, 92))
        );

        jTabbedPaneAbas.addTab("Atividade Turística", jAbaAtividadesTuristicas);

        jAbaAcomodocacoes.setPreferredSize(new java.awt.Dimension(937, 488));

        jLabelPasso1Acom.setText("Passo 1: Selecione o subtipo:");

        jComboAcom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hotel", "Hostelling", "Resort", "Pousada", "Camping", "Bed&Breakfast", "ApartHotel", " ", " ", " ", " " }));
        jComboAcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAcomActionPerformed(evt);
            }
        });

        jTextFPrecoAcom.setEditable(false);

        jTextAreaObsDescricoes.setColumns(20);
        jTextAreaObsDescricoes.setEditable(false);
        jTextAreaObsDescricoes.setRows(5);
        jScrollPaneObsAcom.setViewportView(jTextAreaObsDescricoes);

        jLabelObsAcom.setText("Observacões :");

        jLabelPasso2Acom.setText("Passo 2: Selecione um ítem para visualizá-lo:");

        jLabelLocalAcom.setText("Local:");

        jLabelDiariaAcom.setText("Preço da diária:");

        jButtonAtualizarAcomodacaoSelec.setText("Atualizar");
        jButtonAtualizarAcomodacaoSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarAcomodacaoSelecActionPerformed(evt);
            }
        });

        jLabelNomeAcom.setText("Nome: ");

        jTextFNomeAcom.setEditable(false);

        jLabelNumeroAcom.setText("Numero:");

        jTextFNumeroAcom.setEditable(false);

        jLabelQuartosAcom.setText("Quartos: ");

        jTextFQuartosAcom.setEditable(false);

        jLabelClassifAcom.setText("Classificação:");

        jTextFClasifAcom.setEditable(false);

        jButtonAdicionarAcom.setText("Adicionar");

        jButtonSelecionarAcomodacao.setText("Selecionar");
        jButtonSelecionarAcomodacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarAcomodacaoAcomodacaoActionPerformed(evt);
            }
        });

        jTextFLocalAcom.setEditable(false);

        jLabelAcomEspecificoA.setText("Atividades extras:");

        jTextAreaAcomEspecificoA.setColumns(20);
        jTextAreaAcomEspecificoA.setEditable(false);
        jTextAreaAcomEspecificoA.setRows(5);
        jScrollPaneAcomEspecificoA.setViewportView(jTextAreaAcomEspecificoA);

        jButtonCancelarAcom.setText("Cancelar");

        javax.swing.GroupLayout jAbaAcomodocacoesLayout = new javax.swing.GroupLayout(jAbaAcomodocacoes);
        jAbaAcomodocacoes.setLayout(jAbaAcomodocacoesLayout);
        jAbaAcomodocacoesLayout.setHorizontalGroup(
            jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                                .addComponent(jLabelPasso2Acom)
                                .addGap(41, 41, 41))
                            .addComponent(jComboAcomSelec, 0, 254, Short.MAX_VALUE)
                            .addComponent(jComboAcom, javax.swing.GroupLayout.Alignment.TRAILING, 0, 254, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAtualizarAcomodacaoSelec)
                            .addComponent(jButtonSelecionarAcomodacao))
                        .addGap(586, 586, 586))
                    .addComponent(jLabelPasso1Acom)
                    .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                        .addComponent(jScrollPaneAcomEspecificoA, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelarAcom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdicionarAcom))
                    .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                        .addComponent(jLabelDiariaAcom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFPrecoAcom, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelQuartosAcom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFQuartosAcom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelObsAcom)
                    .addComponent(jScrollPaneObsAcom, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeAcom)
                            .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFLocalAcom)
                                    .addComponent(jTextFNomeAcom, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                            .addComponent(jLabelLocalAcom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                                .addComponent(jLabelNumeroAcom)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFNumeroAcom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                                .addComponent(jLabelClassifAcom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFClasifAcom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelAcomEspecificoA))
                .addContainerGap())
        );

        jAbaAcomodocacoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAtualizarAcomodacaoSelec, jButtonSelecionarAcomodacao});

        jAbaAcomodocacoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFPrecoAcom, jTextFQuartosAcom});

        jAbaAcomodocacoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdicionarAcom, jButtonCancelarAcom});

        jAbaAcomodocacoesLayout.setVerticalGroup(
            jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPasso1Acom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizarAcomodacaoSelec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPasso2Acom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboAcomSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecionarAcomodacao))
                .addGap(9, 9, 9)
                .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeAcom)
                            .addComponent(jTextFNomeAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLocalAcom)
                            .addComponent(jTextFLocalAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroAcom)
                            .addComponent(jTextFNumeroAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFClasifAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelClassifAcom))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jAbaAcomodocacoesLayout.createSequentialGroup()
                        .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDiariaAcom)
                            .addComponent(jTextFPrecoAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelQuartosAcom)
                            .addComponent(jTextFQuartosAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelObsAcom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneObsAcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabelAcomEspecificoA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneAcomEspecificoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jAbaAcomodocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAdicionarAcom)
                        .addComponent(jButtonCancelarAcom)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPaneAbas.addTab("Acomodação", jAbaAcomodocacoes);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CityTour", "Translado", " " }));

        jLabel1.setText("Paso 1: selecione o servico");

        jButtonAtuServ.setText("Atualizar");
        jButtonAtuServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtuServActionPerformed(evt);
            }
        });

        jLabel2.setText("Passo 2: Selecione um ítem para visualizá-lo:");

        jButton1.setText("Selecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome: ");

        jLabel4.setText("Numero:");

        jLabel5.setText("Classificação:");

        jLabel6.setText("Vagas:");

        jLabel7.setText("Preço:");

        jLabel8.setText("Dia:");

        jLabel9.setText("Mes:");

        jLabel10.setText("Ano:");

        jLabel11.setText("Duração:");

        jLabel12.setText("Hora:");

        jLabel13.setText("Min:");

        jButton2.setText("Cancelar");

        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Descrição:");

        jTextADescServ.setColumns(20);
        jTextADescServ.setRows(5);
        jScrollPane1.setViewportView(jTextADescServ);

        javax.swing.GroupLayout jTextFMinServLayout = new javax.swing.GroupLayout(jTextFMinServ);
        jTextFMinServ.setLayout(jTextFMinServLayout);
        jTextFMinServLayout.setHorizontalGroup(
            jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFMinServLayout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(29, 29, 29))
            .addGroup(jTextFMinServLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTextFMinServLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jTextFMinServLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFDurServ, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jTextFMinServLayout.createSequentialGroup()
                        .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBServ, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 167, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jTextFMinServLayout.createSequentialGroup()
                                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFMinServLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(5, 5, 5)))
                                    .addComponent(jLabel8))
                                .addGap(4, 4, 4)
                                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFNomeServ)
                                    .addGroup(jTextFMinServLayout.createSequentialGroup()
                                        .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFDiaServ, 0, 0, Short.MAX_VALUE)
                                            .addComponent(jTextFVagasServ, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(jTextFHoraServ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFPrecoServ, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                            .addGroup(jTextFMinServLayout.createSequentialGroup()
                                                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFMesServ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFAnoServ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAtuServ)
                            .addGroup(jTextFMinServLayout.createSequentialGroup()
                                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFClasServ)
                                    .addComponent(jTextFNumServ, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))))))
                .addGap(183, 183, 183))
        );
        jTextFMinServLayout.setVerticalGroup(
            jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTextFMinServLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAtuServ)
                    .addGroup(jTextFMinServLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(24, 24, 24)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFNomeServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFNumServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFClasServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFVagasServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFPrecoServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFDiaServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFMesServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextFAnoServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFHoraServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFDurServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTextFMinServLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jTextFMinServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGap(26, 26, 26))
                    .addGroup(jTextFMinServLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPaneAbas.addTab("Outros Serviços", jTextFMinServ);

        javax.swing.GroupLayout jAbaDescontosLayout = new javax.swing.GroupLayout(jAbaDescontos);
        jAbaDescontos.setLayout(jAbaDescontosLayout);
        jAbaDescontosLayout.setHorizontalGroup(
            jAbaDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        jAbaDescontosLayout.setVerticalGroup(
            jAbaDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jTabbedPaneAbas.addTab("Descontos", jAbaDescontos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtulizarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtulizarAtividadeActionPerformed
        //Leitora e jCombo Para Ventura
        if(jComboBAtiv.getSelectedItem().equals("Aventura"))
        {
                  
                try{

                        //Leitora do arquivo para cadastro de novas aventuras
                        FileInputStream stream = new FileInputStream("AtividadeAventura.txt");
                        InputStreamReader streamReader = new InputStreamReader(stream);
                        BufferedReader in = new BufferedReader(streamReader);
                        System.out.println("Leitor de arquvo criado.");
                        jComboBAtivSelec.removeAllItems();

                        while((leitor = in.readLine()) != null)
                        {

                                if(linhas == 0)
                                {
                                   jComboBAtivSelec.addItem(leitor);
                                    linhas ++;
                                }    
                                if(leitor.equals("//")){
                                    linhas = 0;
                                    separador = true;
                                }
                            if(leitor == null&&separador == true){break; }            
                        }

                        streamReader.close();
                        in.close();
                        stream.close();
                        System.out.println("Atulizo1");

                }catch(IOException e )
                {
                    System.out.println(e);
                }
                System.out.println("Aventura");
                    jLabelAtivEspecificoA.setVisible(true);
                    jTextFAtivEspecificoA.setVisible(true);
                    jScrollPaneAtivEspecificoB.setVisible(true);
                    jLabelAtivEspecificoB.setVisible(true);
                    jLabelAtivEspecificoA.setText("Dificuldade:");
                    jLabelAtivEspecificoB.setText("Restrições:");
        }
        

        /*if (jComboBAtiv.getSelectedItem().equals("Aventura"))
               {
                    System.out.println("Aventura");
                    jLabelAtivEspecificoA.setVisible(true);
                    jTextFAtivEspecificoA.setVisible(true);
                    jScrollPaneAtivEspecificoB.setVisible(true);
                    jLabelAtivEspecificoB.setVisible(true);
                    jLabelAtivEspecificoA.setText("Dificuldade:");
                    jLabelAtivEspecificoB.setText("Restrições:");
               }*/
        else if(jComboBAtiv.getSelectedItem().equals("Cultural"))
        { 
                  
                try{
                        //Leitora do arquivo para cadastro de novas aventuras
                        FileInputStream stream = new FileInputStream("AtividadeCultural.txt");
                        InputStreamReader streamReader = new InputStreamReader(stream);
                        BufferedReader in = new BufferedReader(streamReader);
                        System.out.println("Leitor de arquvo criado.");
                        jComboBAtivSelec.removeAllItems();

                        while((leitor = in.readLine()) != null)
                        {

                                if(linhas == 0)
                                {
                                   jComboBAtivSelec.addItem(leitor);
                                    linhas ++;
                                }    
                                if(leitor.equals("//")){
                                    linhas = 0;
                                    separador = true;
                                }
                            if(leitor == null&&separador == true){break; }            
                        }

                        streamReader.close();
                        in.close();
                        stream.close();
                        System.out.println("Atulizo1");

                }catch(IOException e )
                {
                    System.out.println(e);
                }
                   
                   
                   System.out.println("Cultura");
                   jLabelAtivEspecificoA.setVisible(false);
                   jTextFAtivEspecificoA.setVisible(false);
                   jScrollPaneAtivEspecificoB.setVisible(false);
                   jLabelAtivEspecificoB.setVisible(false);
        }
        
        
        else if(jComboBAtiv.getSelectedItem().equals("Passeio"))
        {
    
                try{
                        //Leitora do arquivo para cadastro de novas aventuras
                        FileInputStream stream = new FileInputStream("AtividadePasseio.txt");
                        InputStreamReader streamReader = new InputStreamReader(stream);
                        BufferedReader in = new BufferedReader(streamReader);
                        System.out.println("Leitor de arquvo criado.");
                        jComboBAtivSelec.removeAllItems();
                        while((leitor = in.readLine()) != null)
                        {

                                if(linhas == 0)
                                {
                                   jComboBAtivSelec.addItem(leitor);
                                    linhas ++;
                                }    
                                if(leitor.equals("//")){
                                    linhas = 0;
                                    separador = true;
                                }
                            if(leitor == null&&separador == true){break; }            
                        }
                        streamReader.close();
                        in.close();
                        stream.close();
                        System.out.println("Atulizo1");

                }catch(IOException e )
                {
                    System.out.println(e);
                }
                    System.out.println("PAsseio");
                    jLabelAtivEspecificoA.setVisible(false);
                    jTextFAtivEspecificoA.setVisible(false);
                    jScrollPaneAtivEspecificoB.setVisible(true);
                    jLabelAtivEspecificoB.setVisible(true);
                    jLabelAtivEspecificoB.setText("Restrições:");
        }
        else if(jComboBAtiv.getSelectedItem().equals("Alimentacao"))
               {
                     
                try{

                        //Leitora do arquivo para cadastro de novas aventuras
                        FileInputStream stream = new FileInputStream("AtividadeAlimentacao.txt");
                        InputStreamReader streamReader = new InputStreamReader(stream);
                        BufferedReader in = new BufferedReader(streamReader);
                        System.out.println("Leitor de arquvo criado.");
                        jComboBAtivSelec.removeAllItems();

                        while((leitor = in.readLine()) != null)
                        {

                                if(linhas == 0)
                                {
                                   jComboBAtivSelec.addItem(leitor);
                                    linhas ++;
                                }    
                                if(leitor.equals("//")){
                                    linhas = 0;
                                    separador = true;
                                }
                            if(leitor == null&&separador == true){break; }            
                        }

                        streamReader.close();
                        in.close();
                        stream.close();
                        System.out.println("Atulizo1");

                }catch(IOException e )
                {
                    System.out.println(e);
                }
                    System.out.println("Alimentação");
                    jLabelAtivEspecificoA.setVisible(true);
                    jTextFAtivEspecificoA.setVisible(true);
                    jScrollPaneAtivEspecificoB.setVisible(true);
                    jLabelAtivEspecificoB.setVisible(true);
                    jLabelAtivEspecificoA.setText("Classificação:");
                    jLabelAtivEspecificoB.setText("Cardápio:");
               }
    }//GEN-LAST:event_jButtonAtulizarAtividadeActionPerformed


    private void jButtonSelecionarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarAtividadeActionPerformed
        String arquivo = null;
        jComboBAtiv.getSelectedItem();
        if(jComboBAtiv.getSelectedItem().equals("Aventura"))
        {arquivo = "AtividadeAventura.txt";        }
        else if(jComboBAtiv.getSelectedItem().equals("Cultural"))
        {arquivo = "AtividadeCultural.txt";   }
        else if (jComboBAtiv.getSelectedItem().equals("Passeio"))
        { arquivo = "AtividadePasseio.txt";   }
        else if(jComboBAtiv.getSelectedItem().equals("Alimentacao"))
        { arquivo = "AtividadeAlimentacao.txt" ;  }
        try
            {
               
                //Leitora do arquivo para cadastro de novas aventuras
                FileInputStream stream = new FileInputStream(arquivo);
                InputStreamReader streamReader = new InputStreamReader(stream);
                BufferedReader in = new BufferedReader(streamReader);
               //ystem.out.println("Leitor de arquvo criado.");
               
                
                linhas = 0;
                
                while((leitor = in.readLine()) != null)
                {
                    
                    if(jComboBAtivSelec.getSelectedItem().equals(leitor))
                    {    
                        
                        jTextFNomeAtividade.setText(leitor);
                        for(int aux=0;aux<16;aux++)
                        {
                            
                            leitor = in.readLine();
                            switch(aux)
                            {
                                case 1:
                                    jTextFNumerAtividade.setText(leitor);
                                    break;
                                case 2:
                                    //jTextFSubTipoAtividade.setText(leitor);
                                    break;
                                case 3:
                                    jTextFDesAtividade.setText(leitor);
                                    break;
                                case 4:
                                    jTextFAnoAtividade.setText(leitor);
                                    break;
                                case 5:
                                    jTextFMesAtividade.setText(leitor);
                                    break;
                                case 6:
                                    jTextFMesAtividade.setText(leitor);
                                    break;
                                case 7:
                                    jTextFHoraAtividade.setText(leitor);
                                    break;
                                case 8:
                                    
                                    jTextFMinAtividade.setText(leitor);
                                    break;
                                case 9:
                                    jTextFPrecoAtividade.setToolTipText(leitor);
                                    break;
                                case 10:
                                    jTextFLocalAtividade.setText(leitor);
                                    break;
                                case 11:
                                    jTextVagasAtividade.setText(leitor);
                                    break;
                                case 12:
                                    jTextFAtivEspecificoA.setText(leitor);
                                    break;
                                case 13:
                                    jTextAtivEspecificoB.setToolTipText(leitor);
                                    break;
                                default:
                                    linhas= 0;
                                    break;
                            }
                            linhas++;
                        }
                    }
                    linhas++;
                }
               
                streamReader.close();
                in.close();
                stream.close();
                System.out.println("Atulizo Aventura");
        
        }catch(IOException e )
        {
            System.out.println(e);
        }

        if (jComboAcom.getSelectedIndex() == 3)
               {
                    jLabelAcomEspecificoA.setVisible(true);
                    jScrollPaneAcomEspecificoA.setVisible(true);
                   jLabelAtivEspecificoA.setText("Atividades extras:");
               }
        else if(jComboAcom.getSelectedIndex() == 7)
               {
            jLabelAcomEspecificoA.setVisible(true);
            jScrollPaneAcomEspecificoA.setVisible(true);
                   jLabelAtivEspecificoA.setText("Equipamentos extras:");
               }
        else{
            jLabelAcomEspecificoA.setVisible(false);
            jScrollPaneAcomEspecificoA.setVisible(false);
               }
    }//GEN-LAST:event_jButtonSelecionarAtividadeActionPerformed

    private void jComboBAtivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBAtivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBAtivActionPerformed

    private void jComboBAtivSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBAtivSelecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBAtivSelecActionPerformed

    private void jButtonSelecionarAcomodacaoAcomodacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarAcomodacaoAcomodacaoActionPerformed
         if(jComboAcom.getSelectedItem().equals("Hotel"))
        { arquivo = "AcomodacaoHotel.txt"; }
        else if (jComboAcom.getSelectedItem().equals("Hostelling"))
        { arquivo = "AcomodacaoHostelling.txt"; }
        else if (jComboAcom.getSelectedItem().equals("Resort"))
        { arquivo = "AcomodacaoResort.txt"; }
        else if(jComboAcom.getSelectedItem().equals("Pousada"))
        { arquivo = "AcomodacaoPousada.txt"; }
        else if (jComboAcom.getSelectedItem().equals("Camping"))
        { arquivo = "AcomodacaoCamping.txt"; }
        else if(jComboAcom.getSelectedItem().equals("Bed&Breakfast"))
        { arquivo = "AcomodacaoBed&Breakfast.txt"; }
        else if (jComboAcom.getSelectedItem().equals("ApartHotel"))
        { arquivo = "AcomodacaoAparHotel.txt"; }
        try
            {
               
                //Leitora do arquivo para cadastro de novas aventuras
                FileInputStream stream = new FileInputStream(arquivo);
                InputStreamReader streamReader = new InputStreamReader(stream);
                BufferedReader in = new BufferedReader(streamReader);
               //ystem.out.println("Leitor de arquvo criado.");
               
                
                linhas = 0;
                
                while((leitor = in.readLine()) != null)
                {
                    
                    if(jComboAcomSelec.getSelectedItem().equals(leitor))
                    {    
                        
                        jTextFNomeAcom.setText(leitor);
                        for(int aux=0;aux<16;aux++)
                        {
                            
                            leitor = in.readLine();
                            switch(aux)
                            {
                                case 0:
                                    jTextFPrecoAcom.setText(leitor);
                                    break;
                                case 1:
                                    jTextFNumeroAcom.setText(leitor);
                                    break;
                                case 2:
                                   // jTextFDesAtividade.setText(leitor);
                                    break;
                                case 3:
                                    jTextFLocalAcom.setText(leitor);
                                    break;
                                case 4:
                                    jTextFClasifAcom.setText(leitor);
                                    break;
                                case 5:
                                    jTextAreaObsDescricoes.setText(leitor);
                                    break;                        
                                case 6:        
                                    jTextFQuartosAcom.setText(leitor);
                                    break;
                              /*  case 9:
                                    jTextFPrecoAtividade.setToolTipText(leitor);
                                    break;
                                case 10:
                                    jTextFLocalAtividade.setText(leitor);
                                    break;
                                case 11:
                                    jTextVagasAtividade.setText(leitor);
                                    break;
                                case 12:
                                    jTextFAtivEspecificoA.setText(leitor);
                                    break;
                                case 13:
                                    jTextAtivEspecificoB.setToolTipText(leitor);
                                    break;*/
                                default:
                                    linhas= 0;
                                    break;
                            }
                            linhas++;
                        }
                    }
                    linhas++;
                }
               
                streamReader.close();
                in.close();
                stream.close();
                
        
        }catch(IOException e )
        {
            System.out.println(e);
        }
}//GEN-LAST:event_jButtonSelecionarAcomodacaoAcomodacaoActionPerformed

    private void jButtonAtualizarAcomodacaoSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarAcomodacaoSelecActionPerformed
        if(jComboAcom.getSelectedItem().equals("Hotel"))
        { arquivo = "AcomodacaoHotel.txt"; }
        else if (jComboAcom.getSelectedItem().equals("Hostelling"))
        { arquivo = "AcomodacaoHostelling.txt"; }
        else if (jComboAcom.getSelectedItem().equals("Resort"))
        { arquivo = "AcomodacaoResort.txt"; }
        else if(jComboAcom.getSelectedItem().equals("Pousada"))
        { arquivo = "AcomodacaoPousada.txt"; }
        else if (jComboAcom.getSelectedItem().equals("Camping"))
        { arquivo = "AcomodacaoCamping.txt"; }
        else if(jComboAcom.getSelectedItem().equals("Bed&Breakfast"))
        { arquivo = "AcomodacaoBed&Breakfast.txt"; }
        else if (jComboAcom.getSelectedItem().equals("ApartHotel"))
        { arquivo = "AcomodacaoAparHotel.txt"; }
        try {
            //Leitora do arquivo para cadastro de novas aventuras
            FileInputStream stream = new FileInputStream(arquivo);
            InputStreamReader streamReader = new InputStreamReader(stream);
            BufferedReader in = new BufferedReader(streamReader);
            System.out.println("Leitor de arquvo criado.");


            jComboAcomSelec.removeAllItems();

            while((leitor = in.readLine()) != null) {

                if(linhas == 0) {
                    jComboAcomSelec.addItem(leitor);
                    linhas ++;
                }
                if(leitor.equals("//")){
                    linhas = 0;
                    separador = true;
                }
                if(leitor == null&&separador == true){break; }


            }



            streamReader.close();
            in.close();
            stream.close();
            System.out.println("Atulizo1");

        }catch(IOException e ) {
            System.out.println(e);
        }





    }//GEN-LAST:event_jButtonAtualizarAcomodacaoSelecActionPerformed

    private void jComboAcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAcomActionPerformed

}//GEN-LAST:event_jComboAcomActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonAtuServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtuServActionPerformed
        // Atualizar Serviços
        
        
        if(jComboBox1.getSelectedItem().equals("CityTour"))
        { arquivo = "OutrosCityTour.txt"; }
        else if (jComboBox1.getSelectedItem().equals("Translado"))
        { arquivo = "OutrosTranslado.txt"; }
        try {
            //Leitora do arquivo para cadastro de novas aventuras
            FileInputStream stream = new FileInputStream(arquivo);
            InputStreamReader streamReader = new InputStreamReader(stream);
            BufferedReader in = new BufferedReader(streamReader);
            System.out.println("Leitor de arquvo criado.");


            jComboBServ.removeAllItems();

            while((leitor = in.readLine()) != null) {

                if(linhas == 0) {
                    jComboBServ.addItem(leitor);
                    linhas ++;
                }
                if(leitor.equals("//")){
                    linhas = 0;
                    separador = true;
                }
                if(leitor == null&&separador == true){break; }


            }



            streamReader.close();
            in.close();
            stream.close();
            System.out.println("Atulizo1");

        }catch(IOException e ) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonAtuServActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jComboBox1.getSelectedItem().equals("CityTour"))
        { arquivo = "OutrosCityTour.txt"; }
        else if (jComboBox1.getSelectedItem().equals("Translado"))
        { arquivo = "OutrosTranslado.txt"; }
         { arquivo = "OutrosTranslado.txt"; }
        try
            {
               
                //Leitora do arquivo para cadastro de novas aventuras
                FileInputStream stream = new FileInputStream(arquivo);
                InputStreamReader streamReader = new InputStreamReader(stream);
                BufferedReader in = new BufferedReader(streamReader);
               //ystem.out.println("Leitor de arquvo criado.");
               
                
                linhas = 0;
                
                while((leitor = in.readLine()) != null)
                {
                    
                    if(jComboBServ.getSelectedItem().equals(leitor))
                    {    
                        
                        jTextFNomeServ.setText(leitor);
                        for(int aux=0;aux<16;aux++)
                        {
                            
                            leitor = in.readLine();
                            switch(aux)
                            {
                                case 0:
                                    jTextFNumServ.setText(leitor);
                                    break;
                                case 1:
                                    jTextFClasServ.setText(leitor);
                                    break;
                                case 2:
                                    jTextFAnoServ.setText(leitor);
                                    break;
                                case 3:
                                    jTextFMesServ.setText(leitor);
                                    break;
                                case 4:
                                    jTextFDiaServ.setText(leitor);
                                    break;
                                case 5:
                                    jTextFHoraServ.setText(leitor);
                                    break;
                                case 6:
                                    jTextField2.setText(leitor);
                                    break;
                                case 7:
                                    jTextFDurServ.setText(leitor);
                                    break;                        
                                case 8:        
                                    jTextFVagasServ.setText(leitor);
                                    break;
                                case 9:
                                    jTextFPrecoServ.setText(leitor);
                                    break;
                                case 10:
                                    jTextADescServ.setText(leitor);
                                    break;
                                
                               /* case 13:
                                    jTextAtivEspecificoB.setToolTipText(leitor);
                                    break;*/
                                default:
                                    linhas= 0;
                                    break;
                            }
                            linhas++;
                        }
                    }
                    linhas++;
                }
               
                streamReader.close();
                in.close();
                stream.close();
                
        
        }catch(IOException e )
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAdicionarAcom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAcom1ActionPerformed
     
         System.out.println(jT.item);
    }//GEN-LAST:event_jButtonAdicionarAcom1ActionPerformed

    private void jButtonCancelarAcom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAcom1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelarAcom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Adicionar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jAbaAcomodocacoes;
    private javax.swing.JPanel jAbaAtividadesTuristicas;
    private javax.swing.JPanel jAbaDescontos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdicionarAcom;
    private javax.swing.JButton jButtonAdicionarAcom1;
    private javax.swing.JButton jButtonAtuServ;
    private javax.swing.JButton jButtonAtualizarAcomodacaoSelec;
    private javax.swing.JButton jButtonAtulizarAtividade;
    private javax.swing.JButton jButtonCancelarAcom;
    private javax.swing.JButton jButtonCancelarAcom1;
    private javax.swing.JButton jButtonSelecionarAcomodacao;
    private javax.swing.JButton jButtonSelecionarAtividade;
    private javax.swing.JComboBox jComboAcom;
    private javax.swing.JComboBox jComboAcomSelec;
    private javax.swing.JComboBox jComboBAtiv;
    private javax.swing.JComboBox jComboBAtivSelec;
    private javax.swing.JComboBox jComboBServ;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAcomEspecificoA;
    private javax.swing.JLabel jLabelAnoAtiv;
    private javax.swing.JLabel jLabelAtivEspecificoA;
    private javax.swing.JLabel jLabelAtivEspecificoB;
    private javax.swing.JLabel jLabelClassifAcom;
    private javax.swing.JLabel jLabelDescricaoAtiv;
    private javax.swing.JLabel jLabelDiaAtiv;
    private javax.swing.JLabel jLabelDiariaAcom;
    private javax.swing.JLabel jLabelDuracaoAtiv;
    private javax.swing.JLabel jLabelHoraAtiv;
    private javax.swing.JLabel jLabelLocalAcom;
    private javax.swing.JLabel jLabelLocalAtiv;
    private javax.swing.JLabel jLabelMesAtiv;
    private javax.swing.JLabel jLabelMinAtiv;
    private javax.swing.JLabel jLabelNomeAcom;
    private javax.swing.JLabel jLabelNomeAtiv;
    private javax.swing.JLabel jLabelNumeroAcom;
    private javax.swing.JLabel jLabelNumeroAtiv;
    private javax.swing.JLabel jLabelObsAcom;
    private javax.swing.JLabel jLabelPasso1Acom;
    private javax.swing.JLabel jLabelPasso1Ativ;
    private javax.swing.JLabel jLabelPasso2Acom;
    private javax.swing.JLabel jLabelPasso2Ativ;
    private javax.swing.JLabel jLabelPrecoAtiv;
    private javax.swing.JLabel jLabelQuartosAcom;
    private javax.swing.JLabel jLabelVagasAtiv;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneAcomEspecificoA;
    private javax.swing.JScrollPane jScrollPaneAtivEspecificoB;
    private javax.swing.JScrollPane jScrollPaneObsAcom;
    private javax.swing.JTabbedPane jTabbedPaneAbas;
    private javax.swing.JTextArea jTextADescServ;
    private javax.swing.JTextArea jTextAreaAcomEspecificoA;
    private javax.swing.JTextArea jTextAreaObsDescricoes;
    private javax.swing.JTextPane jTextAtivEspecificoB;
    private javax.swing.JTextField jTextFAnoAtividade;
    private javax.swing.JTextField jTextFAnoServ;
    private javax.swing.JTextField jTextFAtivEspecificoA;
    private javax.swing.JTextField jTextFClasServ;
    private javax.swing.JTextField jTextFClasifAcom;
    private javax.swing.JTextField jTextFDesAtividade;
    private javax.swing.JTextField jTextFDiaAtividade;
    private javax.swing.JTextField jTextFDiaServ;
    private javax.swing.JTextField jTextFDurServ;
    private javax.swing.JTextField jTextFDuracaoAtividade;
    private javax.swing.JTextField jTextFHoraAtividade;
    private javax.swing.JTextField jTextFHoraServ;
    private javax.swing.JTextField jTextFLocalAcom;
    private javax.swing.JTextField jTextFLocalAtividade;
    private javax.swing.JTextField jTextFMesAtividade;
    private javax.swing.JTextField jTextFMesServ;
    private javax.swing.JTextField jTextFMinAtividade;
    private javax.swing.JPanel jTextFMinServ;
    private javax.swing.JTextField jTextFNomeAcom;
    private javax.swing.JTextField jTextFNomeAtividade;
    private javax.swing.JTextField jTextFNomeServ;
    private javax.swing.JTextField jTextFNumServ;
    private javax.swing.JTextField jTextFNumerAtividade;
    private javax.swing.JTextField jTextFNumeroAcom;
    private javax.swing.JTextField jTextFPrecoAcom;
    private javax.swing.JTextField jTextFPrecoAtividade;
    private javax.swing.JTextField jTextFPrecoServ;
    private javax.swing.JTextField jTextFQuartosAcom;
    private javax.swing.JTextField jTextFVagasServ;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextVagasAtividade;
    // End of variables declaration//GEN-END:variables
}
